### ISSUE TITLE
504 Gateway Time-out

### ISSUE THREAD

**Issue by Aarevalo3108** [fcoagz/consulta-dolar-venezuela#2]
https://exchange.vcoud.com/coins/latest 

not currently working

**Comment by Aarevalo3108** [comment]
reject(new AxiosError(
           ^
AxiosError: Request failed with status code 504

**Comment by fcoagz** [comment]
Buenos días @Aarevalo3108, pasa a que la API que se está realizando la solicitud tiene retraso en la obtención de los datos, el tiempo de espera pasa el límite, el servidor estaría en funcionamiento en un rato

**Comment by Aarevalo3108** [comment]
gracias! @fcoagz  es bueno saberlo, ya me estaba presentando un error parecido pero con un proveedor de baileys, ya que estoy usando esta API para un bot de whatsapp, me di cuenta de que era la API por los logs

**Comment by fcoagz** [comment]
Así es @Aarevalo3108, de igual forma puedes irte a la API de pyDolarVenezuela, podrás realizar solicitudes de diferentes páginas informativas. Se encuentra en mis repositorio fijados en mi cuenta de github, saludos
